#!/bin/sh
set -e

SQLX_OFFLINE=1 cross build --target x86_64-unknown-linux-musl --release --verbose
SQLX_OFFLINE=1 cross build --target aarch64-unknown-linux-musl --release --verbose

mkdir -p release/terrashine-aarch64-unknown-linux-musl
mkdir -p release/terrashine-x86_64-unknown-linux-musl

cp -a target/x86_64-unknown-linux-musl/release/terrashine release/terrashine-x86_64-unknown-linux-musl/terrashine
cp -a target/aarch64-unknown-linux-musl/release/terrashine release/terrashine-aarch64-unknown-linux-musl/terrashine